name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    
    strategy:
      matrix:
        destination: ['iOS Simulator,name=iPhone 11']
        swift-version: [5.1]

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild -project XYJSON.xcodeproj -scheme XYJSON -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
